---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/ansible/openstack.yaml
  vars:
    network_name: boom
    os_host: 192.168.42.133
    os_password: d6ef8d5e38314435
    
  tasks:
    - debug: var=playbook_dir

    # - name: Copy OS_CLIENT_CONFIG_FILE
    #   copy:
    #     src: "{{ playbook_dir }}/../scratch/openstack.yaml"
    #     dest: /etc/ansible/openstack.yaml

    - name: Create OS_CLIENT_CONFIG_FILE
      template:
        src: "{{ playbook_dir }}/../templates/openstack.yaml.j2"
        dest: /etc/ansible/openstack.yaml

    - name: Authenticate to specified OpenStack provider
    # https://docs.ansible.com/ansible/os_auth_module.html
      os_auth:
        cloud: mycloud

    # Create an externally accessible network named 'ext_network'.
    - os_network:
        cloud: mycloud
        state: present
        name: "{{ network_name }}"
        external: true