---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local
  # vars_files:
  #   - "../group_vars/all/vars"
  tasks:
    # - debug: var=manageiq
    # - debug: var=manageiq.api_url
    # - debug: var=manageiq.api_token
    # - debug: var=manageiq.service

    # - name: Authenticate to the cloud and retrieve the service catalog
    #   os_auth:
    #     # cloud: whatever
    #     auth:
    #       auth_url: 'http://192.168.42.132:5000/v2.0'
    #       username: 'admin'
    #       password: bdee3d85b0264ad4
    #     validate_certs: no

    # Create a project
    - os_project:
        cloud: mycloud
        state: present
        name: demoproject
        description: demodescription
        # domain_id: demoid
        enabled: True

    # Delete a project
    # - os_project:
    #     cloud: mycloud
    #     state: absent
    #     name: demoproject