---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local
  # vars_files:
  #   - "../group_vars/all/vars"
  environment:
    OS_CLIENT_CONFIG_FILE: /etc/ansible/openstack.yaml

  tasks:
    # - debug: var=manageiq
    # - debug: var=manageiq.api_url
    # - debug: var=manageiq.api_token
    # - debug: var=manageiq.service

    - name: Authenticate to the cloud and retrieve the service catalog
    # https://docs.ansible.com/ansible/os_auth_module.html
      os_auth:
        cloud: mycloud
        # auth:
        #   auth_url: http://192.168.42.132:5000/v2.0
        #   username: admin
        #   password: bdee3d85b0264ad4
        #   # project_name: admin
        # validate_certs: no

    # Gather facts about previously created projects
    # - os_project_facts:
    #     cloud: mycloud
    # - debug:
    #     var: openstack_projects

    # # Gather facts about a previously created project by name
    # - os_project_facts:
    #     cloud: mycloud
    #     name: admin
    # - debug:
    #     var: openstack_projects

    # Create a project
    - os_project:
        cloud: mycloud
        state: present
        name: demoproject
        description: demodescription
        domain_id: default
        enabled: True

    # Delete a project
    # - os_project:
    #     cloud: mycloud
    #     state: absent
    #     name: demoproject